name: ItemFlangerorimega
main: no.runsafe.itemflangerorimega.Plugin
version: 1.0.@BUILD@
author: Kruithne
description: Custom item handling
commands:
  enchantbow:
    description: Enchants a bow with some form of wizardry.
