name: ItemFlangerorimega
main: no.runsafe.itemflangerorimega.Plugin
version: 1.0.@BUILD@
author: Kruithne
description: Custom item handling
commands:
  customenchant:
    description: Enchants an item with some form of wizardry.
    aliases: [cenchant]
  boxitem:
    description: Derpy piston spawning