name: ItemFlangerorimega
main: no.runsafe.itemflangerorimega.Plugin
version: 1.0.@BUILD@
author: Kruithne
depend: [RunsafeWorldGuardBridge]
description: Custom item handling
commands:
  customenchant:
    description: Enchants an item with some form of wizardry.
    aliases: [cenchant]
  scaffolding:
    description: Spawn a stack of scaffolding